version: "3"

services: 
    jupyter:
        build: ./jupyter_aula
        restart: always
        environment: 
            - JUPYTER_ENABLE_LAB=yes
            - JUPYTER_TOKEN=aula
            - NB_UID=1000
            - NB_GUID=1000
            - RESTARTABLE=yes
            - TZ=America/Araguaina
            - DEBIAN_FRONTEND=noninteractive
        ports: 
            - 8888:8888
            - 6006:6006
        volumes:
            - $HOME/notebooks:/tf/work