version: "3"

services: 
    jupyter:
        build: ./jupyter_aula
        environment: 
            - JUPYTER_ENABLE_LAB=yes
        ports: 
            - 8888:8888
            - 6006:6006
        volumes: 
            - ./data/home:/tf/work